services:
  postgres:
    image: postgres:16
    container_name: crypto-postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: crypto

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d crypto"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: crypto-app
    restart: unless-stopped

    depends_on:
      postgres:
        condition: service_healthy

    environment:
     CONFIG_PATH: configs/config.docker.yaml
     TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
     DATABASE_PASSWORD: ${DATABASE_PASSWORD}

    ports:
      - "8080:8080"

volumes:
  postgres_data: